# Project Information
site_name: The Works
site_description: Docker container with all the tools you need.
site_url: https://grumpydumpty.github.io/theworks
site_author: Grumpy Dumpty
docs_dir: docs
site_dir: .site
use_directory_urls: true

# Repository
repo_url: https://github.com/grumpydumpty/theworks
edit_uri: blob/main/docs

# Copyright
copyright: |
  Copyright &copy; 1970-2024 Grumpy Dumpty. All rights reserved.<br/><br/>

# Configuration
theme:
  name: material
  favicon: favicon.ico
  logo: assets/images/icon-white.svg
  icon:
    repo: fontawesome/brands/github
  palette:
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: indigo
    accent: indigo
    toggle:
      icon: material/toggle-switch
      name: Dark Theme
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: indigo
    accent: indigo
    toggle:
      icon: material/toggle-switch-off-outline
      name: Light Theme
  font:
    text: Roboto
    code: Roboto Mono
  features:
  - content.action.edit
  - content.action.view
  - content.code.annotate
  - content.code.copy
  - content.tabs.link
  - navigation.footer
  - navigation.header
  - navigation.indexes
  - navigation.instant
  - navigation.sections
  - navigation.tabs
  - navigation.tabs.sticky
  - navigation.top
  - navigation.tracking
  - search.highlight
  - search.share
  - search.suggest
  - toc.follow

# Plugins
plugins:
- search:
    separator: '[\s\u200b\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
- open-in-new-tab
- markdownextradata:
    jinja_options:
      variable_start_string: "${{"
      variable_end_string: "}}"
- git-revision-date-localized:
    enabled: !ENV [CI, false]
    enable_creation_date: false
    exclude:
      - index.md
    fallback_to_build_date: true
    type: timeago

# Customization
extra:
  version:
    default: latest
    provider: mike
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/grumpydumpty/theworks
    - icon: fontawesome/solid/book
      link: https://grumpydumpty.github.io/theworks/
    - icon: fontawesome/solid/code
      link: https://github.com/grumpydumpty/theworks/docs
extra_css:
  - assets/stylesheets/extra.css
  - assets/stylesheets/spanable.css

# Extensions
markdown_extensions:
- admonition
- attr_list
- footnotes
- md_in_html
- neoteroi.spantable
- pymdownx.critic
- pymdownx.emoji:
    emoji_index: !!python/name:material.extensions.emoji.twemoji
    emoji_generator: !!python/name:material.extensions.emoji.to_svg
    options:
      custom_icons:
      - material/.icons
- pymdownx.inlinehilite
- pymdownx.highlight:
    use_pygments: true
- pymdownx.snippets:
    check_paths: true
- pymdownx.superfences:
    custom_fences:
    - name: mermaid
      class: mermaid
      format: !!python/name:pymdownx.superfences.fence_code_format
- pymdownx.tabbed:
    alternate_style: true
- pymdownx.details
- tables
- toc:
    permalink: true

# Navigation
nav:
- Overview:
  - index.md
  - Getting Start: getting-started.md
  - Components: components.md
  - GitLab CI/CD: gitlab-ci.md
  - Harbor Repo: harbor.md
  - Release Notes: release-notes.md
  - Release Milestones: https://github.com/grumpydumpty/theworks/milestones
  - License: license.md
- Community:
  - community/index.md
  - Contributing: community/contributing.md
  - Discussions: https://github.com/grumpydumpty/theworks/discussions
  - Search Issues: https://github.com/grumpydumpty/theworks/issues
  - Open an Issue: https://github.com/grumpydumpty/theworks/issues/new
  - Support: community/support.md
  - Code of Conduct: community/code-of-conduct.md
